name: rx_bloc
description: A Flutter package that helps implementing the BLoC (Business Logic Component) Design Pattern using the power of reactive streams.
version: 2.0.0
repository: https://github.com/Prime-Holding/rx_bloc/tree/master/packages/rx_bloc
issue_tracker: https://github.com/Prime-Holding/rx_bloc/issues
homepage: https://www.primeholding.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.26.0
  meta: ^1.3.0

dev_dependencies:
  rx_bloc_test:
  coverage: ^1.0.1
  pedantic: ^1.9.0
  test: ^1.15.2
  mockito: ^5.0.0
  quiver: ^3.0.0


dependency_overrides:
  rx_bloc_test:
    path: ../rx_bloc_test
