name: rx_bloc_test
description: A Flutter package with the goal to enable testing rxBlocs from the FlutterRxBloc package with ease.
version: 0.0.5
repository: https://github.com/Prime-Holding/RxBlocTest
issue_tracker: https://github.com/Prime-Holding/RxBlocTest/issues
homepage: https://primeholding.com

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  test: ^1.15.2
  meta: ^1.1.8
  rx_bloc: ^1.0.1
  mockito: ^4.1.1
  rxdart: ^0.24.1
  quiver: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
