builders:
  rx_block:
    import: "package:rx_bloc_generator/builder.dart"
    builder_factories: ["buildRxBuilder"]
    build_extensions: {'.dart': ['rxb.g.dart']}
    auto_apply: root_package
    build_to: source